version: 0.2

phases:

  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t brain-task-app .
      - docker tag brain-task-app:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest

  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest

artifacts:
  files:
    - deployment.yaml
    - service.yaml